import fs from "fs-extra";
import path from "path";
import { applyMobileChromeChoice } from "./playwrightConfig";

export async function scaffoldProject(targetDir: string, answers: Record<string, any>) {
  const templateDir = path.join(__dirname, "..", "templates", "default");

  await fs.copy(templateDir, targetDir, {
    overwrite: false,
    errorOnExist: false,
    filter: (src) => {
      // The AI assistant guidance file is generated by the caller (via src/aiConfig.ts)
      // instead of copied verbatim — this reference copy would otherwise land at the
      // wrong path/name for whichever tool the user picked.
      if (path.relative(templateDir, src) === "CLAUDE.md") return false;
      // .gitkeep files exist only to keep otherwise-empty template folders (e.g. tests/)
      // alive in git/npm — not meant to actually land in a scaffolded project.
      if (path.basename(src) === ".gitkeep") return false;
      return true;
    },
  });

  await applyMobileChromeChoice(path.join(targetDir, "playwright.config.ts"), Boolean(answers.includeMobileChrome));
  if (!answers.includeMobileChrome) {
    console.log("ℹ️  mobile-chrome (Pixel 5 emulation) project not included — re-run 'testroid init' or edit playwright.config.ts to add it later.");
  }

  const envLines = [`PROJECT_NAME=${answers.projectName}`];
  // Omitted rather than written as `BASE_URL=` when unset: playwright.config.ts falls
  // back to a placeholder via `process.env.BASE_URL ?? '...'`, which only kicks in when
  // the key is absent — an empty string would satisfy `??` and silently point tests at "".
  if (answers.baseUrl) envLines.push(`BASE_URL=${answers.baseUrl}`);
  envLines.push(`SUITE_TYPE=${answers.suiteType}`, `ENVIRONMENT=${answers.environment}`);

  const envContent = envLines.join("\n");

  await fs.writeFile(path.join(targetDir, ".env"), envContent);

  console.log(`✅ Testroid scaffolded into ${targetDir}`);
  console.log(`✅ .env created with your site config`);
}
