import fs from "fs-extra";
import path from "path";

export async function scaffoldProject(targetDir: string, answers: Record<string, any>) {
  const templateDir = path.join(__dirname, "..", "templates", "default");

  await fs.copy(templateDir, targetDir, {
    overwrite: false,
    errorOnExist: false,
    filter: (src) => {
      // The AI assistant guidance file is generated by the caller (via src/aiConfig.ts)
      // instead of copied verbatim — this reference copy would otherwise land at the
      // wrong path/name for whichever tool the user picked.
      if (path.relative(templateDir, src) === "CLAUDE.md") return false;
      // .gitkeep files exist only to keep otherwise-empty template folders (e.g. tests/)
      // alive in git/npm — not meant to actually land in a scaffolded project.
      if (path.basename(src) === ".gitkeep") return false;
      return true;
    },
  });

  const envContent = [
  `PROJECT_NAME=${answers.projectName}`,
  `BASE_URL=${answers.baseUrl}`,
  `SUITE_TYPE=${answers.suiteType}`,
  `ENVIRONMENT=${answers.environment}`
].join("\n");

  await fs.writeFile(path.join(targetDir, ".env"), envContent);

  console.log(`✅ Testroid scaffolded into ${targetDir}`);
  console.log(`✅ .env created with your site config`);
}
